### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by logsverify** [tm31420/Break-Secp256K1-Task-23122.421#2]
Traceback (most recent call last):
  File "C:\Users\Randy\Downloads\Break-Secp256K1-Task-23122.421-main\scanner.py", line 180, in <module>
    scan(address)
  File "C:\Users\Randy\Downloads\Break-Secp256K1-Task-23122.421-main\scanner.py", line 164, in scan
    inputs.append(addrdata['txs'][y]['hash'])
IndexError: list index out of range

**Comment by tm31420** [comment]
that error means you ran out of txids out from the address, check the address and number of txids out from the wallet.

**Comment by logsverify** [comment]
Okay, what does the mean "Enter number of txos to search for"? txs or txid?
